use paselista;
insert into login values("Aldryn Osorio","S3CR3T0");
select* from login;
insert into alumnos values( 1,"Mario","Chico","Sanchez");
SELECT*FROM alumnos;
insert into alumnos values( 2,"Raul","Duarte","Beltran");
insert into alumnos values( 3,"Luis","Fuentes","Mariacas");
insert into alumnos values( 4,"Alex","Brito","?");
insert into alumnos values( 5,"Juan","Lopez","?");
insert into alumnos values( 6,"Marco","Chong","?");
insert into alumnos values( 7,"Javier","Buenfil","Flores");
insert into alumnos values( 8,"Adrian","Ludwig","?");
insert into alumnos values( 9,"Cristian","Peña","Cuevas");
insert into alumnos values( 10,"Samir Rajsaid","Jimenez","Vivas");
insert into alumnos values( 11,"Enrique","Perez","?");
insert into alumnos values( 12,"Victor","Rodriguez","Camacho");
insert into alumnos values( 13,"Jose Esteban","Pereira","Luciano");
insert into alumnos values( 14,"Federico","Sanchez","Diaz");
insert into alumnos values( 15,"Davidsito","Segovia","Ley");
insert into alumnos values( 16,"Jesus","Silva","Marentes");
insert into alumnos values( 17,"Rodrigo","Yerena","?");
select*from alumnos;